services:
- type: web
  name: al-serverless-Render-NJA
  runtime: node
  repo: https://github.com/NOKIMIMO/al-serverless-Render
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: node-db
      property: connectionString
  region: frankfurt
  buildCommand: npm install
  startCommand: npm start

- type: web
  name: al-serverless-static
  runtime: static
  repo: https://github.com/NOKIMIMO/al-serverless-static
  staticPublishPath: ./
  routes:
  - type: redirect
    source: /photo
    destination: https://th.bing.com/th/id/R.e78f8e7c326d3e7cdcf053d58f494542?rik=bXopo7rm0XIdFQ&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2fc%2fc7%2fDomestic_shorthaired_cat_face.jpg&ehk=NByReFekRNa%2fCe0v9gNPEb0tpYmVhy4kI5uaC1l1AUI%3d&risl=1&pid=ImgRaw&r=0
version: "1"

databases:
  - name: node-db
    plan: free
    region: frankfurt